# Generated by Django 2.2.6 on 2020-10-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_arrival', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='animals_image/%Y/%m/%d')),
            ],
        ),
    ]
