# Generated by Django 3.1.2 on 2020-10-08 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100, null=True)),
                ('eye_color', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('certificate', models.BooleanField(default=False)),
                ('date_of_arrival', models.DateField(default=datetime.date.today)),
                ('kind_of_animal', models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('P', 'Parrot')], default='C', max_length=2)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(blank=True, upload_to='static/images/animals_image/%Y/%m/%d')),
            ],
        ),
    ]
