# Generated by Django 2.2.6 on 2020-10-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0002_breed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Breed',
        ),
    ]
