# Generated by Django 2.2.6 on 2020-10-05 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0003_delete_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='date_of_arrival',
        ),
    ]
