# Generated by Django 2.2.6 on 2020-10-05 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0004_remove_animal_date_of_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_of_arrival',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
