# Generated by Django 2.2.6 on 2020-10-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0005_animal_date_of_arrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='kind_of_animal',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog'), ('P', 'Parrot')], default='C', max_length=2),
        ),
    ]
