# Generated by Django 2.2.6 on 2020-10-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0006_animal_kind_of_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='eye_color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
