# Generated by Django 2.2.6 on 2020-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0007_auto_20201005_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images/animals_image/%Y/%m/%d'),
        ),
    ]
