# Generated by Django 3.1.2 on 2020-10-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0008_auto_20201007_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='breed',
        ),
    ]
