# Generated by Django 3.1.2 on 2020-10-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_shelter', '0009_remove_animal_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
